<?php

namespace SimplyTestable\ApiBundle\Tests\Controller\Job\Job\StatusAction;

use SimplyTestable\ApiBundle\Tests\Controller\Job\Job\Access\TeamAccess\CreatedByMemberAccessedByDifferentMemberTest as BaseCreatedByMemberAccessedByDifferentMemberTest;

class CreatedByMemberAccessedByDifferentMemberTest extends BaseCreatedByMemberAccessedByDifferentMemberTest {}