sudo: false
services:
  - redis-server

language: php
php:
  - 5.6
  - 7
  - 7.1

env:
  - SYMFONY_ENV=test

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update
  - phpenv config-add travis.php.ini
  - cp .travis.composer.config.json ~/.composer/config.json
  - mv app/config/parameters.yml.travis app/config/parameters.yml
  - mv --force app/config/config_travis.yml app/config/config_test.yml
  - cp src/SimplyTestable/ApiBundle/Resources/config/parameters.yml.dist.yml src/SimplyTestable/ApiBundle/Resources/config/parameters.yml
  - echo 'active' > src/SimplyTestable/ApiBundle/Resources/config/state/test
  - mysql -e 'CREATE DATABASE myapp_test;'

install:
  - composer install --prefer-dist
  - php bin/console doctrine:migrations:migrate --no-interaction
  - php bin/console doctrine:fixtures:load --append
  - composer config --global process-timeout 2000

before_script:
  - php bin/console --env=test cache:clear
  - php bin/console --env=test cache:warmup

script:
  - composer test

matrix:
  allow_failures:
  - php: 7.1
