services:
  - redis-server
  - memcache

language: php

php:
  - 5.5
  - 5.6
  - 7

before_script:
  - cp .travis.composer.config.json ~/.composer/config.json

  # Build!
  - mkdir app/cache/test
  - mv app/config/parameters.yml.travis app/config/parameters.yml
  - mv --force app/config/config_travis.yml app/config/config_test.yml
  - cp src/SimplyTestable/ApiBundle/Resources/config/parameters.yml.dist.yml src/SimplyTestable/ApiBundle/Resources/config/parameters.yml
  - composer install
  - php app/console doctrine:database:create
  - php app/console doctrine:migrations:migrate --no-interaction
  - php app/console doctrine:fixtures:load --append

script:
  - composer test
