language: php
php:
  - 5.3
  - 5.4
  
before_script:    
  # Installing pecl_http module
  - printf "\n\n\n\n" | pecl -q install pecl_http
  - echo "extension=http.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`  
  
  # Install composer for dependency management
  - wget http://getcomposer.org/composer.phar 
  
  # Set the GitHub OAuth token to make use of the 6000 per hour rate limit
  - "mkdir -p ~/.composer"
  - cp .travis.composer.config.json ~/.composer/config.json    
  
  # Build!
  #- mysql -e "create database myapp_test;"
  #- mkdir app/cache
  - mkdir app/cache/test  
  - mv app/config/parameters.yml.travis app/config/parameters.yml
  - mv --force app/config/config_travis.yml app/config/config_test.yml
  - echo | php composer.phar install
  - php app/console doctrine:database:create
  - php app/console doctrine:migrations:migrate --no-interaction
  #- php app/console doctrine:database:create
  #- build/phing/bin/phing build:install:ci:travis
  
script:
  - phpunit -c app