language: php
php:
  - 5.3
  - 5.4
  
before_script:  
  # Installing phing
  - git clone https://github.com/phingofficial/phing.git build/phing
  
  # Installing pecl_http module
  - printf "\n\n\n\n" | pecl -q install pecl_http
  - echo "extension=http.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`  
  
  # Install composer for dependency management
  - wget http://getcomposer.org/composer.phar 
  
  # Build!
  #- phing build:install:ci:travis
  - build/phing/bin/phing build:install:ci:travis
  
script:
  - phpunit -c app