imports:
    - { resource: parameters.yml }
    - { resource: "@SimplyTestableApiBundle/Resources/config/parameters.yml" }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    #trust_proxy_headers: false # Should Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:
      handler_id: simplytestable.session.handler

sensio_framework_extra:
  router:
    annotations: false

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: SimplyTestable\ApiBundle\Entity\User
    service:
        mailer: fos_user.mailer.noop
    from_email:
        address: user@example.com
        sender_name: "null"

resque:
    prefix: "%bcc_resque_prefix%"                # optional prefix to separate Resque data per site/app
