imports:
    - { resource: parameters.yml }
    - { resource: "@SimplyTestableApiBundle/Resources/config/parameters.yml" }
    - { resource: security.yml }
    - { resource: "@SimplyTestableApiBundle/Resources/config/services.yml" }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    #trust_proxy_headers: false # Should Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:
      handler_id: simplytestable.session.handler

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

mz_postmark:
    api_key:    %postmark_api_key%
    from_email: %postmark_from_email%
    from_name:  %postmark_from_name%
    use_ssl:    %postmark_use_ssl%
    timeout:    %postmark_timeout%

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: SimplyTestable\ApiBundle\Entity\User
    service:
        mailer: fos_user.mailer.noop
    from_email:
        address: user@example.com
        sender_name: "null"

jms_serializer:
    metadata:
        directories:
            FOSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/config/serializer/FOSUB"

# BCCResqueBundle Configuration
bcc_resque:
    #class: BCC\ResqueBundle\Resque           # the resque class if different from default
    #vendor_dir: %kernel.root_dir%/../vendor  # the vendor dir if different from default
    prefix: %bcc_resque_prefix%                # optional prefix to separate Resque data per site/app
    #redis:
    #    host: localhost                      # the redis host
    #    port: 6379                           # the redis port
    #    database: 1                          # the redis database
    #auto_retry: [0, 10, 60]                  # auto retry failed jobs
    #worker:
    #    root_dir: path/to/worker/root        # the root dir of app that run workers (optional)