imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

sensio_framework_extra:
  router:
    annotations: false

resque:
    prefix: "%bcc_resque_prefix%"                # optional prefix to separate Resque data per site/app
