imports:
    - { resource: config_dev.yml }
    - { resource: "@SimplyTestableApiBundle/Resources/config/parameters_test.yml" }    
    - { resource: services_test.yml }      

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
    
parameters:    
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: ci_app_simplytestable_com
    database_user: root
    database_password: root
