imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
    
parameters:    
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: test_app_simplytestable_com
    database_user: st_app_test
    database_password: st_app_test_password
