imports:
    - { resource: config_test.yml }
    
parameters:    
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: myapp_test
    database_user: root
    database_password: null
