services:
  simplytestable.services.websiteservice:
    class:  SimplyTestable\ApiBundle\Services\WebSiteService
    arguments: 
        entityManager: "@doctrine.orm.entity_manager"
        
  simplytestable.services.stateservice:
    class:  SimplyTestable\ApiBundle\Services\StateService
    arguments: 
        entityManager: "@doctrine.orm.entity_manager"        
        
  simplytestable.services.jobservice:
    class:  SimplyTestable\ApiBundle\Services\JobService
    arguments: 
        entityManager: "@doctrine.orm.entity_manager"
        
  simplytestable.services.userservice:
    class:  SimplyTestable\ApiBundle\Services\UserService
    arguments:
        encoderFactory: "@security.encoder_factory"
        usernameCanonicalizer: "@fos_user.util.username_canonicalizer"
        emailCanonicalizer: "@fos_user.util.email_canonicalizer"
        objectManager: "@doctrine.orm.entity_manager"
        class: %fos_user.model.user.class%      