<?php

namespace SimplyTestable\ApiBundle\Tests\Functional\Controller\Job\Job\TaskIdsAction;

use SimplyTestable\ApiBundle\Tests\Functional\Controller\Job\Job\Access\TeamAccess\CreatedByMemberAccessedByDifferentMemberTest as BaseCreatedByMemberAccessedByDifferentMemberTest;

class CreatedByMemberAccessedByDifferentMemberTest extends BaseCreatedByMemberAccessedByDifferentMemberTest {}