<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120716191654_create_State extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE State (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, nextState_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_6252FDFF5E237E06 (name), UNIQUE INDEX UNIQ_6252FDFF4A689548 (nextState_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE State ADD CONSTRAINT FK_6252FDFF4A689548 FOREIGN KEY (nextState_id) REFERENCES State (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE State DROP FOREIGN KEY FK_6252FDFF4A689548");
        $this->addSql("DROP TABLE State");
    }
}
