<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120716214726_create_Worker_Job_TaskType_Task extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Worker (id INT AUTO_INCREMENT NOT NULL, url VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_981EBA54F47645AE (url), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Job (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, website_id INT DEFAULT NULL, state_id INT DEFAULT NULL, INDEX IDX_C395A618A76ED395 (user_id), INDEX IDX_C395A61818F45C82 (website_id), INDEX IDX_C395A6185D83CC1 (state_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE TaskType (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_F7737B3C5E237E06 (name), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Task (id INT AUTO_INCREMENT NOT NULL, job_id INT DEFAULT NULL, state_id INT DEFAULT NULL, worker_id INT DEFAULT NULL, url LONGTEXT NOT NULL, INDEX IDX_F24C741BBE04EA9 (job_id), INDEX IDX_F24C741B5D83CC1 (state_id), INDEX IDX_F24C741B6B20BA36 (worker_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE Job ADD CONSTRAINT FK_C395A618A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)");
        $this->addSql("ALTER TABLE Job ADD CONSTRAINT FK_C395A61818F45C82 FOREIGN KEY (website_id) REFERENCES WebSite (id)");
        $this->addSql("ALTER TABLE Job ADD CONSTRAINT FK_C395A6185D83CC1 FOREIGN KEY (state_id) REFERENCES State (id)");
        $this->addSql("ALTER TABLE Task ADD CONSTRAINT FK_F24C741BBE04EA9 FOREIGN KEY (job_id) REFERENCES Job (id)");
        $this->addSql("ALTER TABLE Task ADD CONSTRAINT FK_F24C741B5D83CC1 FOREIGN KEY (state_id) REFERENCES State (id)");
        $this->addSql("ALTER TABLE Task ADD CONSTRAINT FK_F24C741B6B20BA36 FOREIGN KEY (worker_id) REFERENCES Worker (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Task DROP FOREIGN KEY FK_F24C741B6B20BA36");
        $this->addSql("ALTER TABLE Task DROP FOREIGN KEY FK_F24C741BBE04EA9");
        $this->addSql("DROP TABLE Worker");
        $this->addSql("DROP TABLE Job");
        $this->addSql("DROP TABLE TaskType");
        $this->addSql("DROP TABLE Task");
    }
}
