<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120716235415_update_Job_add_not_null_fields extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Job CHANGE website_id website_id INT NOT NULL, CHANGE state_id state_id INT NOT NULL, CHANGE user_id user_id INT NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Job CHANGE user_id user_id INT DEFAULT NULL, CHANGE website_id website_id INT DEFAULT NULL, CHANGE state_id state_id INT DEFAULT NULL");
    }
}
