<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120713222405 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Worker (id INT AUTO_INCREMENT NOT NULL, url VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_981EBA54F47645AE (url), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Job (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, website_id INT NOT NULL, state_id INT NOT NULL, INDEX user_index (user_id), INDEX website_index (website_id), INDEX state_index (state_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE State (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, nextState_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_6252FDFF5E237E06 (name), UNIQUE INDEX UNIQ_6252FDFF4A689548 (nextState_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE TaskType (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_F7737B3C5E237E06 (name), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Task (id INT AUTO_INCREMENT NOT NULL, job_id INT NOT NULL, url LONGTEXT NOT NULL, state_id INT NOT NULL, worker_id INT DEFAULT NULL, INDEX job_index (job_id), INDEX url_index (url(255)), INDEX state_index (state_id), INDEX worker_index (worker_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE State ADD CONSTRAINT FK_6252FDFF4A689548 FOREIGN KEY (nextState_id) REFERENCES State (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE State DROP FOREIGN KEY FK_6252FDFF4A689548");
        $this->addSql("DROP TABLE Worker");
        $this->addSql("DROP TABLE Job");
        $this->addSql("DROP TABLE State");
        $this->addSql("DROP TABLE TaskType");
        $this->addSql("DROP TABLE Task");
    }
}
