<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120724124825_add_class_and_description_to_Task extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");        
       
        $this->addSql("ALTER TABLE TaskType ADD tasktypeclass_id INT NOT NULL, ADD description LONGTEXT NOT NULL");
        $this->addSql("ALTER TABLE TaskType ADD CONSTRAINT FK_F7737B3CAEA19A54 FOREIGN KEY (tasktypeclass_id) REFERENCES TaskTypeClass (id)");
        $this->addSql("CREATE INDEX IDX_F7737B3CAEA19A54 ON TaskType (tasktypeclass_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE TaskType DROP FOREIGN KEY FK_F7737B3CAEA19A54");
        $this->addSql("ALTER TABLE TaskType DROP FOREIGN KEY FK_F7737B3CAEA19A54");
        $this->addSql("DROP INDEX IDX_F7737B3CAEA19A54 ON TaskType");
        $this->addSql("ALTER TABLE TaskType DROP tasktypeclass_id, DROP description");
    }
}
