<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120724153426_create_JobTaskTypes extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE JobTaskTypes (tasktype_id INT NOT NULL, job_id INT NOT NULL, INDEX IDX_6520FB147D6EFC3 (tasktype_id), INDEX IDX_6520FB14BE04EA9 (job_id), PRIMARY KEY(tasktype_id, job_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE JobTaskTypes ADD CONSTRAINT FK_6520FB147D6EFC3 FOREIGN KEY (tasktype_id) REFERENCES TaskType (id)");
        $this->addSql("ALTER TABLE JobTaskTypes ADD CONSTRAINT FK_6520FB14BE04EA9 FOREIGN KEY (job_id) REFERENCES Job (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE JobTaskTypes");
    }
}
