<?php

namespace Application\Migrations;

use SimplyTestable\BaseMigrationsBundle\Migration\BaseMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130122113752_create_JobType extends BaseMigration
{
    public function up(Schema $schema)
    {
        $this->statements['mysql'] = array(
            "CREATE TABLE JobType (
                id INT AUTO_INCREMENT NOT NULL,
                name VARCHAR(255) NOT NULL,
                description LONGTEXT NOT NULL,
                UNIQUE INDEX UNIQ_6AEF4BE05E237E06 (name),
                PRIMARY KEY(id))
                DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB"
//            "CREATE TABLE TaskType (
//                id INT AUTO_INCREMENT NOT NULL,
//                name VARCHAR(255) NOT NULL,
//                tasktypeclass_id INT NOT NULL,
//                description LONGTEXT NOT NULL,
//                selectable TINYINT(1) NOT NULL,
//                UNIQUE INDEX UNIQ_F7737B3C5E237E06 (name),
//                INDEX IDX_F7737B3CAEA19A54 (tasktypeclass_id),
//                PRIMARY KEY(id)) ENGINE = InnoDB",
//            "ALTER TABLE TaskType ADD CONSTRAINT FK_F7737B3CAEA19A54 FOREIGN KEY (tasktypeclass_id) REFERENCES TaskTypeClass (id)"
        );
        
        $this->statements['sqlite'] = array(
//            "CREATE TABLE TaskType (
//                id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
//                name VARCHAR(255) NOT NULL,
//                tasktypeclass_id INT NOT NULL,
//                description LONGTEXT NOT NULL,
//                selectable TINYINT(1) NOT NULL,
//                FOREIGN KEY(tasktypeclass_id) REFERENCES TaskTypeClass (id))",
//            "CREATE UNIQUE INDEX UNIQ_F7737B3C5E237E06 ON TaskType (name)",
//            "CREATE INDEX IDX_F7737B3CAEA19A54 ON TaskType (tasktypeclass_id)"
            "CREATE TABLE JobType (
                id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                name VARCHAR(255) NOT NULL,
                description LONGTEXT NOT NULL,
                PRIMARY KEY(id))",
            "CREATE UNIQUE INDEX UNIQ_6AEF4BE05E237E06 ON JobType (name)",
        ); 
        
        parent::up($schema);
    }
   

    public function down(Schema $schema)
    {           
        $this->addCommonStatement("DROP TABLE JobType");      
        
        parent::down($schema);
    }     
    
//    public function up(Schema $schema)
//    {
//        // this up() migration is autogenerated, please modify it to your needs
//        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
//        
//        $this->addSql("CREATE TABLE JobType (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, UNIQUE INDEX UNIQ_6AEF4BE05E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
//    }
//
//    public function down(Schema $schema)
//    {
//        // this down() migration is autogenerated, please modify it to your needs
//        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
//        
//        $this->addSql("DROP TABLE JobType");
//    }
}
