services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FOS\UserBundle\Security\LoginManager:
    public: true
    alias: fos_user.security.login_manager

  AppBundle\Services\HttpClientService:
    class:   Tests\AppBundle\Services\TestHttpClientService
    arguments:
      - '%curl_options%'

  # Need to inject our guzzle client into the postmark client to enable regular HTTP mocking in tests
  # We don't to this for the dev/prod service as Postmark\PostmarkClient depends on the client constructor being
  # passed the base url for correct behaviour.
  Postmark\PostmarkClient:
    arguments:
        - '%env(POSTMARK_API_KEY)%'
    calls:
      - [setClient, ['@GuzzleHttp\Client']]
