services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FOS\UserBundle\Security\LoginManager:
    public: true
    alias: fos_user.security.login_manager

  App\Services\HttpClientService:
    class:   App\Tests\Services\TestHttpClientService
    arguments:
      - '%curl_options%'

  # Need to inject our guzzle client into the postmark client to enable regular HTTP mocking in tests
  # We don't to this for the dev/prod service as Postmark\PostmarkClient depends on the client constructor being
  # passed the base url for correct behaviour.
  Postmark\PostmarkClient:
    arguments:
        - '%env(POSTMARK_API_KEY)%'
    calls:
      - [setClient, ['@GuzzleHttp\Client']]

  App\Tests\Services\ConstraintFactory:
    public: true

  App\Tests\Services\JobAmmendmentFactory:
    public: true

  App\Tests\Services\JobTaskConfigurationFactory:
    public: true

  App\Tests\Services\JobConfigurationFactory:
    public: true

  App\Tests\Services\JobFactory:
    public: true

  App\Tests\Services\UserAccountPlanFactory:
    public: true

  App\Tests\Services\UserFactory:
    public: true

  App\Tests\Services\JobLoader:
    public: true

  App\Tests\Services\StripeEventFactory:
    public: true

  App\Tests\Services\PlanFactory:
    public: true

  App\Tests\Services\ScheduledJobFactory:
    public: true
