services:
  simplytestable.command.cron.run:
    class:  SimplyTestable\ApiBundle\Command\Cron\RunCommand
    tags:
      - { name: console.command }

  simplytestable.command.job.enqueueprepareall:
    class:  SimplyTestable\ApiBundle\Command\Job\EnqueuePrepareAllCommand
    arguments:
      resqueQueueService: '@simplytestable.services.resque.queueservice'
      resqueJobFactory: '@simplytestable.services.resque.jobfactoryservice'
      stateService: '@simplytestable.services.stateservice'
      entityManager: '@doctrine.orm.entity_manager'
      applicationStateService: '@simplytestable.services.applicationstateservice'
    tags:
      - { name: console.command }

  simplytestable.command.job.completealwithnoincompletetasks:
    class:  SimplyTestable\ApiBundle\Command\Job\CompleteAllWithNoIncompleteTasksCommand
    arguments:
      applicationStateService: '@simplytestable.services.applicationstateservice'
      jobService: '@simplytestable.services.jobservice'
    tags:
      - { name: console.command }

  simplytestable.command.job.prepare:
    class:  SimplyTestable\ApiBundle\Command\Job\PrepareCommand
    arguments:
      applicationStateService: '@simplytestable.services.applicationstateservice'
      resqueQueueService: '@simplytestable.services.resque.queueservice'
      resqueJobFactory: '@simplytestable.services.resque.jobfactoryservice'
      jobService: '@simplytestable.services.jobservice'
      jobPreparationService: '@simplytestable.services.jobpreparationservice'
      crawlJobContainerService: '@simplytestable.services.crawljobcontainerservice'
      logger: '@logger'
      predefinedDomainsToIgnore:
        css-validation: '%css-validation-domains-to-ignore%'
        js-static-analysis: '%js-static-analysis-domains-to-ignore%'
    tags:
      - { name: console.command }
