services:
  simplytestable.command.cron.run:
    class:  SimplyTestable\ApiBundle\Command\Cron\RunCommand
    tags:
      - { name: console.command }

  simplytestable.command.job.enqueueprepareall:
    class:  SimplyTestable\ApiBundle\Command\Job\EnqueuePrepareAllCommand
    arguments:
      resqueQueueService: '@simplytestable.services.resque.queueservice'
      resqueJobFactory: '@simplytestable.services.resque.jobfactory'
      stateService: '@simplytestable.services.stateservice'
      entityManager: '@doctrine.orm.entity_manager'
      applicationStateService: '@simplytestable.services.applicationstateservice'
    tags:
      - { name: console.command }

  simplytestable.command.job.completealwithnoincompletetasks:
    class:  SimplyTestable\ApiBundle\Command\Job\CompleteAllWithNoIncompleteTasksCommand
    arguments:
      applicationStateService: '@simplytestable.services.applicationstateservice'
      jobService: '@simplytestable.services.jobservice'
    tags:
      - { name: console.command }

  simplytestable.command.job.prepare:
    class:  SimplyTestable\ApiBundle\Command\Job\PrepareCommand
    arguments:
      applicationStateService: '@simplytestable.services.applicationstateservice'
      resqueQueueService: '@simplytestable.services.resque.queueservice'
      resqueJobFactory: '@simplytestable.services.resque.jobfactory'
      jobService: '@simplytestable.services.jobservice'
      jobPreparationService: '@simplytestable.services.jobpreparationservice'
      crawlJobContainerService: '@simplytestable.services.crawljobcontainerservice'
      logger: '@logger'
      predefinedDomainsToIgnore:
        css-validation: '%css-validation-domains-to-ignore%'
        js-static-analysis: '%js-static-analysis-domains-to-ignore%'
    tags:
      - { name: console.command }

  simplytestable.command.job.resolvewebsite:
    class:  SimplyTestable\ApiBundle\Command\Job\ResolveWebsiteCommand
    arguments:
      applicationStateService: '@simplytestable.services.applicationstateservice'
      resqueQueueService: '@simplytestable.services.resque.queueservice'
      resqueJobFactory: '@simplytestable.services.resque.jobfactory'
      jobService: '@simplytestable.services.jobservice'
      websiteResolutionService: '@simplytestable.services.jobwebsiteresolutionservice'
      jobPreparationService: '@simplytestable.services.jobpreparationservice'
      predefinedDomainsToIgnore:
        css-validation: '%css-validation-domains-to-ignore%'
        js-static-analysis: '%js-static-analysis-domains-to-ignore%'
    tags:
      - { name: console.command }

  simplytestable.command.maintenance.disablereadonly:
    class:  SimplyTestable\ApiBundle\Command\Maintenance\DisableReadOnlyCommand
    arguments:
      applicationStateService: '@simplytestable.services.applicationstateservice'
    tags:
      - { name: console.command }

  simplytestable.command.maintenance.enablebackupreadonly:
    class:  SimplyTestable\ApiBundle\Command\Maintenance\EnableBackupReadOnlyCommand
    arguments:
      applicationStateService: '@simplytestable.services.applicationstateservice'
    tags:
      - { name: console.command }

  simplytestable.command.maintenance.enablereadonly:
    class:  SimplyTestable\ApiBundle\Command\Maintenance\EnableReadOnlyCommand
    arguments:
      applicationStateService: '@simplytestable.services.applicationstateservice'
    tags:
      - { name: console.command }

  simplytestable.command.maintenance.modifyinitialstarttrialperiod:
    class:  SimplyTestable\ApiBundle\Command\Maintenance\ModifyInitialStartTrialPeriodCommand
    arguments:
      accountPlanService: '@simplytestable.services.accountplanservice'
      userAccountPlanService: '@simplytestable.services.useraccountplanservice'
      entityManager: '@doctrine.orm.entity_manager'
    tags:
      - { name: console.command }

  simplytestable.command.reporting.getoutputidsforerror:
    class:  SimplyTestable\ApiBundle\Command\Reporting\GetOutputIdsForErrorCommand
    arguments:
      taskTypeService: '@simplytestable.services.tasktypeservice'
      entityManager: '@doctrine.orm.entity_manager'
    tags:
      - { name: console.command }