services:
  SimplyTestable\ApiBundle\EventListener\Stripe\CustomerSubscriptionDeletedListener:
    arguments:
      - '@SimplyTestable\ApiBundle\Services\StripeEventService'
      - '@GuzzleHttp\Client'
      - '@doctrine.orm.entity_manager'
      - '%web_client%'
      - '@SimplyTestable\ApiBundle\Services\StripeService'
      - '@SimplyTestable\ApiBundle\Services\UserAccountPlanService'
      - '@SimplyTestable\ApiBundle\Services\AccountPlanService'
    tags:
      - { name: kernel.event_listener, event: stripe_process.customer.subscription.deleted, method: onCustomerSubscriptionDeleted }

  SimplyTestable\ApiBundle\EventListener\Stripe\CustomerSubscriptionCreatedListener:
    arguments:
      - '@SimplyTestable\ApiBundle\Services\StripeEventService'
      - '@GuzzleHttp\Client'
      - '@doctrine.orm.entity_manager'
      - '%web_client%'
      - '@SimplyTestable\ApiBundle\Services\StripeService'
      - '@SimplyTestable\ApiBundle\Services\UserAccountPlanService'
    tags:
      - { name: kernel.event_listener, event: stripe_process.customer.subscription.created, method: onCustomerSubscriptionCreated }

  SimplyTestable\ApiBundle\EventListener\Stripe\CustomerSubscriptionTrialWillEndListener:
    arguments:
      - '@SimplyTestable\ApiBundle\Services\StripeEventService'
      - '@GuzzleHttp\Client'
      - '@doctrine.orm.entity_manager'
      - '%web_client%'
      - '@SimplyTestable\ApiBundle\Services\StripeService'
      - '@SimplyTestable\ApiBundle\Services\UserAccountPlanService'
    tags:
      - { name: kernel.event_listener, event: stripe_process.customer.subscription.trial_will_end, method: onCustomerSubscriptionTrialWillEnd }

  SimplyTestable\ApiBundle\EventListener\Stripe\CustomerSubscriptionUpdatedListener:
    arguments:
      - '@SimplyTestable\ApiBundle\Services\StripeEventService'
      - '@GuzzleHttp\Client'
      - '@doctrine.orm.entity_manager'
      - '%web_client%'
      - '@SimplyTestable\ApiBundle\Services\StripeService'
      - '@SimplyTestable\ApiBundle\Services\UserAccountPlanService'
      - '@SimplyTestable\ApiBundle\Services\AccountPlanService'
    tags:
      - { name: kernel.event_listener, event: stripe_process.customer.subscription.updated, method: onCustomerSubscriptionUpdated }

  SimplyTestable\ApiBundle\EventListener\Stripe\InvoicePaymentSucceededListener:
    arguments:
      - '@SimplyTestable\ApiBundle\Services\StripeEventService'
      - '@GuzzleHttp\Client'
      - '@doctrine.orm.entity_manager'
      - '%web_client%'
    tags:
      - { name: kernel.event_listener, event: stripe_process.invoice.payment_succeeded, method: onInvoicePaymentSucceeded }

  SimplyTestable\ApiBundle\EventListener\Stripe\InvoicePaymentFailedListener:
    arguments:
      - '@SimplyTestable\ApiBundle\Services\StripeEventService'
      - '@GuzzleHttp\Client'
      - '@doctrine.orm.entity_manager'
      - '%web_client%'
      - '@SimplyTestable\ApiBundle\Services\StripeService'
      - '@SimplyTestable\ApiBundle\Services\UserAccountPlanService'
      - '@event_dispatcher'
    tags:
      - { name: kernel.event_listener, event: stripe_process.invoice.payment_failed, method: onInvoicePaymentFailed }
