services:
  simplytestable.repository.task:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\Task\Task

  simplytestable.repository.state:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\State

  simplytestable.repository.worker:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\Worker

  simplytestable.repository.useraccountplan:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\UserAccountPlan

  simplytestable.repository.tasktypeclass:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\Task\Type\TaskTypeClass

  simplytestable.repository.team:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\Team\Team

  simplytestable.repository.user:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\User

  simplytestable.repository.tasktype:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\Task\Type\Type

  simplytestable.repository.jobtype:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\Job\Type

  simplytestable.repository.job:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\Job\Job

  simplytestable.repository.useremailchangerequest:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\UserEmailChangeRequest

  simplytestable.repository.taskoutput:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\Task\Output

  simplytestable.repository.scheduledjob:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\ScheduledJob

  simplytestable.repository.stripeevent:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\Stripe\Event

  simplytestable.repository.userpostactivationproperties:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\UserPostActivationProperties

  simplytestable.repository.workeractivationrequest:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\WorkerActivationRequest

  simplytestable.repository.crawljobcontainer:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\CrawlJobContainer

  simplytestable.repository.jobrejectionreason:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\Job\RejectionReason

  simplytestable.repository.teaminvite:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\Team\Invite
