services:
  simplytestable.repository.workeractivationrequest:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\WorkerActivationRequest

  simplytestable.repository.crawljobcontainer:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\CrawlJobContainer

  simplytestable.repository.jobrejectionreason:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\Job\RejectionReason

  simplytestable.repository.teaminvite:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\Team\Invite
