services:
  simplytestable.services.resque.jobfactory:
    class:  SimplyTestable\ApiBundle\Services\Resque\JobFactory
    public: true
    arguments:
        $queues:
          job-prepare:
            queue: job-prepare
            jobClassName: SimplyTestable\ApiBundle\Resque\Job\Job\PrepareJob
            requiredArgs:
              - id
            serviceIds:
              - simplytestable.services.applicationstateservice
              - simplytestable.services.resque.queueservice
              - simplytestable.services.resque.jobfactory
              - simplytestable.services.jobservice
              - simplytestable.services.jobpreparationservice
              - simplytestable.services.crawljobcontainerservice
              - logger
            parameters:
              predefinedDomainsToIgnore:
                css-validation: '%css-validation-domains-to-ignore%'
                js-static-analysis: '%js-static-analysis-domains-to-ignore%'
          job-resolve:
            queue: job-resolve
            jobClassName: SimplyTestable\ApiBundle\Resque\Job\Job\ResolveJob
            requiredArgs:
              - id
            serviceIds:
              - simplytestable.services.applicationstateservice
              - simplytestable.services.resque.queueservice
              - simplytestable.services.resque.jobfactory
              - simplytestable.services.jobservice
              - simplytestable.services.jobwebsiteresolutionservice
              - simplytestable.services.jobpreparationservice
            parameters:
              predefinedDomainsToIgnore:
                css-validation: '%css-validation-domains-to-ignore%'
                js-static-analysis: '%js-static-analysis-domains-to-ignore%'
          task-assign-collection:
            queue: task-assign-collection
            jobClassName: SimplyTestable\ApiBundle\Resque\Job\Task\AssignCollectionJob
            requiredArgs:
              - ids
            serviceIds:
              - simplytestable.services.applicationstateservice
              - doctrine.orm.entity_manager
              - simplytestable.services.taskpreprocessor.factory
              - simplytestable.services.resque.queueservice
              - simplytestable.services.resque.jobfactory
              - simplytestable.services.stateservice
              - simplytestable.services.workertaskassignmentservice
              - logger
          task-cancel-collection:
            queue: task-cancel-collection
            jobClassName: SimplyTestable\ApiBundle\Resque\Job\Task\CancelCollectionJob
            requiredArgs:
              - ids
            serviceIds:
              - simplytestable.services.applicationstateservice
              - simplytestable.services.taskservice
              - simplytestable.services.workertaskcancellationservice
              - logger
          worker-activate-verify:
            queue: worker-activate-verify
            jobClassName: SimplyTestable\ApiBundle\Resque\Job\Worker\ActivateVerifyJob
            requiredArgs:
              - id
            serviceIds:
              - simplytestable.services.applicationstateservice
              - doctrine.orm.entity_manager
              - simplytestable.services.workeractivationrequestservice
          stripe-event:
            queue: stripe-event
            jobClassName: SimplyTestable\ApiBundle\Resque\Job\Stripe\ProcessEventJob
            requiredArgs:
              - stripeId
            serviceIds:
              - simplytestable.services.applicationstateservice
              - doctrine.orm.entity_manager
              - logger
              - event_dispatcher
          tasks-notify:
            queue: tasks-notify
            jobClassName: SimplyTestable\ApiBundle\Resque\Job\Worker\Tasks\NotifyJob
            serviceIds:
              - simplytestable.services.worker.tasknotificationservice
          scheduledjob-execute:
            queue: scheduledjob-execute
            jobClassName: SimplyTestable\ApiBundle\Resque\Job\ScheduledJob\ExecuteJob
            requiredArgs:
              - id
            serviceIds:
              - simplytestable.services.applicationstateservice
              - simplytestable.services.resque.queueservice
              - simplytestable.services.resque.jobfactory
              - doctrine.orm.entity_manager
              - simplytestable.services.job.startservice
              - simplytestable.services.jobservice
