## Services that need to be public to allow them to be retrieved from the container in functional tests
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  SimplyTestable\ApiBundle\Services\ScheduledJob\Service:

  SimplyTestable\ApiBundle\Services\Job\ConfigurationService:

  SimplyTestable\ApiBundle\Services\WebSiteService:

  SimplyTestable\ApiBundle\Services\Job\StartService:

  SimplyTestable\ApiBundle\Services\JobConfigurationFactory:

  SimplyTestable\ApiBundle\Services\Job\WebsiteResolutionService:

  SimplyTestable\ApiBundle\Services\StripeEventService:

  SimplyTestable\ApiBundle\Services\WorkerActivationRequestService:

  SimplyTestable\ApiBundle\Services\UserService:

  SimplyTestable\ApiBundle\Services\StateService:

  SimplyTestable\ApiBundle\Services\JobTypeService:

  SimplyTestable\ApiBundle\Services\JobPreparationService:

  SimplyTestable\ApiBundle\Services\AccountPlanService:

  SimplyTestable\ApiBundle\Services\ApplicationStateService:

  SimplyTestable\ApiBundle\Services\Resque\QueueService:

  SimplyTestable\ApiBundle\Services\CrawlJobContainerService:

  SimplyTestable\ApiBundle\Services\TaskTypeService:

  SimplyTestable\ApiBundle\Services\Team\Service:

  SimplyTestable\ApiBundle\Services\ApplicationStatusFactory:

  SimplyTestable\ApiBundle\Services\CrawlJobUrlCollector:

  SimplyTestable\ApiBundle\Services\Job\RetrievalService:

  SimplyTestable\ApiBundle\Services\JobListService:

  SimplyTestable\ApiBundle\Services\Request\Factory\Task\CompleteRequestFactory:

  SimplyTestable\ApiBundle\Services\JobSummaryFactory:

  SimplyTestable\ApiBundle\Services\JobService:

  SimplyTestable\ApiBundle\Services\JobUserAccountPlanEnforcementService:

  SimplyTestable\ApiBundle\Services\QueryBuilderFactory\JobListQueryBuilderFactory:

  SimplyTestable\ApiBundle\Services\Request\Factory\Job\ListRequestFactory:

  SimplyTestable\ApiBundle\Services\Request\Factory\Job\StartRequestFactory:

  SimplyTestable\ApiBundle\Services\ResourceLocator:

  SimplyTestable\ApiBundle\Services\Task\QueueService:

  SimplyTestable\ApiBundle\Services\TaskOutputJoiner\LinkIntegrityTaskOutputJoiner:

  SimplyTestable\ApiBundle\Services\TaskPostProcessor\UrlDiscoveryTaskPostProcessor:

  SimplyTestable\ApiBundle\Services\TaskPreProcessor\LinkIntegrityTaskPreProcessor:

  SimplyTestable\ApiBundle\Services\Team\InviteService:

  SimplyTestable\ApiBundle\Services\Team\MemberService:

  SimplyTestable\ApiBundle\Services\UserEmailChangeRequestService:

  SimplyTestable\ApiBundle\Services\UserPostActivationPropertiesService:

  SimplyTestable\ApiBundle\Services\TaskService:

  SimplyTestable\ApiBundle\Services\UserSummaryFactory:

  SimplyTestable\ApiBundle\Services\Worker\TaskNotificationService:

  SimplyTestable\ApiBundle\Services\WorkerTaskAssignmentService:

  SimplyTestable\ApiBundle\Services\UrlDiscoveryTaskService:

  SimplyTestable\ApiBundle\Services\TaskTypeDomainsToIgnoreService:
    arguments:
      $domainsToIgnoreByTaskType:
        "css validation": '%css_validation_domains_to_ignore%'
        "js static analysis": '%js_static_analysis_domains_to_ignore%'

  SimplyTestable\ApiBundle\Services\ScheduledJob\CronModifier\ValidationService:

  SimplyTestable\ApiBundle\Services\WorkerTaskCancellationService:

  SimplyTestable\ApiBundle\Services\UserAccountPlanService:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@SimplyTestable\ApiBundle\Services\UserService'
      - '@SimplyTestable\ApiBundle\Services\StripeService'
      - '@SimplyTestable\ApiBundle\Services\Team\Service'
      - '%default_trial_period%'

  FOS\UserBundle\Security\LoginManager:
    alias: fos_user.security.login_manager

  SimplyTestable\ApiBundle\Services\TaskOutputJoiner\Factory:
    arguments:
      $taskPreprocessors:
        - '@SimplyTestable\ApiBundle\Services\TaskOutputJoiner\LinkIntegrityTaskOutputJoiner'

  SimplyTestable\ApiBundle\Services\TaskPostProcessor\Factory:
    arguments:
      $taskPreprocessors:
        - '@SimplyTestable\ApiBundle\Services\TaskPostProcessor\UrlDiscoveryTaskPostProcessor'

  webignition\WebResource\Sitemap\Factory:

  webignition\WebsiteSitemapFinder\WebsiteSitemapFinder:

  webignition\WebResource\Retriever:
    factory: 'SimplyTestable\ApiBundle\Services\WebResourceRetrieverFactory:create'

  webignition\WebsiteRssFeedFinder\WebsiteRssFeedFinder:

  webignition\Url\Resolver\Resolver:

  SimplyTestable\ApiBundle\Services\StripeWebHookMailNotificationSender:
    arguments:
      $mailService: '@SimplyTestable\ApiBundle\Services\Mail\Service'
      $parameters: "%stripe_webhook_developer_notification%"

  SimplyTestable\ApiBundle\Services\TaskPreProcessor\Factory:
    arguments:
      $taskPreprocessors:
        - '@SimplyTestable\ApiBundle\Services\TaskPreProcessor\LinkIntegrityTaskPreProcessor'

  test.usermanipulator:
    alias: FOS\UserBundle\Util\UserManipulator
