services:
  webignition\ResqueJobFactory\ResqueJobFactory:
    public: true
    arguments:
        $queues:
          job-prepare:
            queue: job-prepare
            jobClassName: SimplyTestable\ApiBundle\Resque\Job\Job\PrepareJob
            requiredArgs:
              - id
            parameters:
              predefinedDomainsToIgnore:
                css-validation: '%css_validation_domains_to_ignore%'
                js-static-analysis: '%js_static_analysis_domains_to_ignore%'
          job-resolve:
            queue: job-resolve
            jobClassName: SimplyTestable\ApiBundle\Resque\Job\Job\ResolveJob
            requiredArgs:
              - id
            parameters:
              predefinedDomainsToIgnore:
                css-validation: '%css_validation_domains_to_ignore%'
                js-static-analysis: '%js_static_analysis_domains_to_ignore%'
          task-assign-collection:
            queue: task-assign-collection
            jobClassName: SimplyTestable\ApiBundle\Resque\Job\Task\AssignCollectionJob
            requiredArgs:
              - ids
          task-cancel-collection:
            queue: task-cancel-collection
            jobClassName: SimplyTestable\ApiBundle\Resque\Job\Task\CancelCollectionJob
            requiredArgs:
              - ids
          worker-activate-verify:
            queue: worker-activate-verify
            jobClassName: SimplyTestable\ApiBundle\Resque\Job\Worker\ActivateVerifyJob
            requiredArgs:
              - id
          stripe-event:
            queue: stripe-event
            jobClassName: SimplyTestable\ApiBundle\Resque\Job\Stripe\ProcessEventJob
            requiredArgs:
              - stripeId
          tasks-notify:
            queue: tasks-notify
            jobClassName: SimplyTestable\ApiBundle\Resque\Job\Worker\Tasks\NotifyJob
          scheduledjob-execute:
            queue: scheduledjob-execute
            jobClassName: SimplyTestable\ApiBundle\Resque\Job\ScheduledJob\ExecuteJob
            requiredArgs:
              - id
