rm -Rf app/cache/prod/ annotations
rm -Rf app/cache/prod/ appProdProjectContainer.php
rm -Rf app/cache/prod/ appprodUrlGenerator.php
rm -Rf app/cache/prod/ appprodUrlMatcher.php
rm -Rf app/cache/prod/ classes.map
rm -Rf app/cache/prod/ classes.php
rm -Rf app/cache/prod/ doctrine
rm -Rf app/cache/prod/ jms_aop
rm -Rf app/cache/prod/ jms_diextra
rm -Rf app/cache/prod/ jms_security
rm -Rf app/cache/prod/ jms_serializer
rm -Rf app/cache/prod/ twig