parameters:
  bcc_resque_prefix: app.simplytestable.com
  resque_pid: "simplytestable_apibundle"
  stripe_webhook_developer_notification:
    recipient_email: jon@simplytestable.com
    sender_email: robot@simplytestable.com
    sender_name: Simply Testable Robot
    subject: Stripe Webhook Data {{ event-type }}
  task_pre_processors:
    link-integrity:
      class: SimplyTestable\ApiBundle\Services\TaskPreProcessor\LinkIntegrityTaskPreProcessor
  task_output_joiners:
    link-integrity:
      class: SimplyTestable\ApiBundle\Services\TaskOutputJoiner\LinkIntegrityTaskOutputJoiner
  web_client:
    urls:
      base: http://ci.gears.simplytestable.com
      stripe_event_controller: /stripe/event/
  stripe_key: "stripe_key_value"
  tasks_per_job_per_worker_count: 2
  cron.command_builder.class: SimplyTestable\ApiBundle\Services\Cron\CommandBuilder\CommandBuilder