glit_resque:
  prefix: "SimplyTestable\ApiBundle"
  
parameters:  
  resque-job-class-map:
    "worker-activate-verify": "SimplyTestable\ApiBundle\Resque\Job\WorkerActivateVerifyJob"
    "job-prepare": "SimplyTestable\ApiBundle\Resque\Job\JobPrepareJob"
    "job-mark-completed": "SimplyTestable\ApiBundle\Resque\Job\JobMarkCompletedJob"
    "task-assign": "SimplyTestable\ApiBundle\Resque\Job\TaskAssignJob"       
    "task-cancel": "SimplyTestable\ApiBundle\Resque\Job\TaskCancelCollectionJob"  
  resque_pid: "simplytestable_apibundle"    
  css-validation-domains-to-ignore:
   - cdnjs.cloudflare.com
   - ajax.googleapis.com
   - netdna.bootstrapcdn.com
   - ajax.aspnetcdn.com
   - static.nrelate.com
  js-static-analysis-domains-to-ignore:
   - cdnjs.cloudflare.com
   - ajax.googleapis.com
   - netdna.bootstrapcdn.com
   - ajax.aspnetcdn.com
   - static.nrelate.com      
  stripe_webhook_developer_notification:
    recipient_email: jon@simplytestable.com
    sender_email: robot@simplytestable.com
    sender_name: Simply Testable Robot
    subject: Stripe Webhook Data {{ event-type }}   