glit_resque:
  prefix: "SimplyTestable\ApiBundle"
  
parameters:  
  resque-job-class-map:
    "worker-activate-verify": "SimplyTestable\ApiBundle\Resque\Job\WorkerActivateVerifyJob"
    "job-prepare": "SimplyTestable\ApiBundle\Resque\Job\JobPrepareJob"
    "job-mark-completed": "SimplyTestable\ApiBundle\Resque\Job\JobMarkCompletedJob"
    "task-assign": "SimplyTestable\ApiBundle\Resque\Job\TaskAssignJob"       
    "task-cancel": "SimplyTestable\ApiBundle\Resque\Job\TaskCancelCollectionJob"
  resque_pid: "simplytestable_apibundle"
  css-validation-domains-to-ignore:
   - cdnjs.cloudflare.com
   - ajax.googleapis.com
   - netdna.bootstrapcdn.com
   - ajax.aspnetcdn.com
   - static.nrelate.com
  js-static-analysis-domains-to-ignore:
   - cdnjs.cloudflare.com
   - ajax.googleapis.com
   - netdna.bootstrapcdn.com
   - ajax.aspnetcdn.com
   - static.nrelate.com   
   - connect.facebook.net   
  stripe_webhook_developer_notification:
    recipient_email: jon@simplytestable.com
    sender_email: robot@simplytestable.com
    sender_name: Simply Testable Robot
    subject: Stripe Webhook Data {{ event-type }}
  task_pre_processors:   
    link-integrity:
      class: SimplyTestable\ApiBundle\Services\TaskPreProcessor\LinkIntegrityTaskPreProcessor
  task_output_joiners:   
    link-integrity:
      class: SimplyTestable\ApiBundle\Services\TaskOutputJoiner\LinkIntegrityTaskOutputJoiner    
  content_type_web_resource_map:
    default: webignition\WebResource\WebResource
    text/html: webignition\WebResource\WebPage\WebPage
    application/xhtml+xml: webignition\WebResource\WebPage\WebPage
    application/json: webignition\WebResource\JsonDocument\JsonDocument      
  web_client:
    urls:
      base: https://gears.simplytestable.com
      stripe_event_controller: /stripe/event/
  stripe_key: "stripe_key_value"