test_start:
    pattern: /tests/{site_root_url}/start/
    defaults: { _controller: SimplyTestableApiBundle:Tests:start, _format: json }
    requirements:
        site_root_url: ".+"
    
task_status:
  pattern: /tasks/{site_root_url}/{test_id}/{task_id}/status/
  defaults: { _controller: SimplyTestableApiBundle:Tests:taskStatus, _format: json } 
  requirements:
    site_root_url: ".+"    
    
test_status:
    pattern: /tests/{site_root_url}/{test_id}/status/
    defaults: { _controller: SimplyTestableApiBundle:Tests:status, _format: json }    
    requirements:
        site_root_url: ".+"
    
test_results:
    pattern: /tests/{site_root_url}/{test_id}/results/
    defaults: { _controller: SimplyTestableApiBundle:Tests:results, _format: json }    
    requirements:
        site_root_url: ".+"
        
test_cancel:
    pattern: /tests/{site_root_url}/{test_id}/cancel/
    defaults: { _controller: SimplyTestableApiBundle:Tests:cancel, _format: json }    
    requirements:
        site_root_url: ".+"        
        
worker_activate:
  pattern: /worker/activate/
  defaults: { _controller: SimplyTestableApiBundle:Worker:activate, _format: json }   
  
task_complete:
  pattern: /task/{worker_hostname}/{remote_task_id}/complete/
  defaults: { _controller: SimplyTestableApiBundle:Task:complete, _format: json }     
        
SimplyTestableApiBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SimplyTestableApiBundle:Default:index }