jobs_list:
    pattern: /jobs/list/{limit}/
    defaults: { _controller: SimplyTestableApiBundle:Job:list, limit: 1, _format: json }    

job_start:
    pattern: /job/{site_root_url}/start/
    defaults: { _controller: SimplyTestableApiBundle:JobStart:start, _format: json }
    requirements:
        site_root_url: ".+"
        
job_tasks:
  pattern: /job/{site_root_url}/{test_id}/tasks/
  defaults: { _controller: SimplyTestableApiBundle:Job:tasks, _format: json } 
  requirements:
    site_root_url: ".+"   
    
job_task_ids:
  pattern: /job/{site_root_url}/{test_id}/tasks/ids/
  defaults: { _controller: SimplyTestableApiBundle:Job:taskIds, _format: json } 
  requirements:
    site_root_url: ".+"     

job_list_urls:
    pattern: /job/{site_root_url}/{test_id}/urls/
    defaults: { _controller: SimplyTestableApiBundle:Job:listUrls, _format: json }    
    requirements:
        site_root_url: ".+"  
        
job_cancel:
    pattern: /job/{site_root_url}/{test_id}/cancel/
    defaults: { _controller: SimplyTestableApiBundle:Job:cancel, _format: json }    
    requirements:
        site_root_url: ".+"            
        
job:
    pattern: /job/{site_root_url}/{test_id}/
    defaults: { _controller: SimplyTestableApiBundle:Job:status, _format: json }    
    requirements:
        site_root_url: ".+"        
    
task_type_count:
  pattern: /tasks/{task_type}/{state_name}/count/
  defaults: { _controller: SimplyTestableApiBundle:Task:taskTypeCount, _format: json }         
   
        
worker_activate:
  pattern: /worker/activate/
  defaults: { _controller: SimplyTestableApiBundle:Worker:activate, _format: json }   
  
task_complete:
  pattern: /task/{worker_hostname}/{remote_task_id}/complete/
  defaults: { _controller: SimplyTestableApiBundle:Task:complete, _format: json }     
  
status:
  pattern: /
  defaults: { _controller: SimplyTestableApiBundle:Status:index, _format: json }     
  
user_create:
  pattern: /user/create/
  defaults: { _controller: SimplyTestableApiBundle:UserCreation:create, _format: json }   

user:
  pattern: /user/{email_canonical}/
  defaults: { _controller: SimplyTestableApiBundle:User:get, _format: json }             
  
user_activate:
  pattern: /user/activate/{token}/
  defaults: { _controller: SimplyTestableApiBundle:UserCreation:activate, _format: json }
  
user_get_token:
  pattern: /user/{email_canonical}/token/
  defaults: { _controller: SimplyTestableApiBundle:User:getToken, _format: json }    
  
user_reset_password:
  pattern: /user/reset-password/{token}/
  defaults: { _controller: SimplyTestableApiBundle:UserPasswordReset:resetPassword, _format: json }
  
user_exists:
  pattern: /user/{email_canonical}/exists/
  defaults: { _controller: SimplyTestableApiBundle:User:exists, _format: json }     
  
user_is_enabled:
  pattern: /user/{email_canonical}/enabled/
  defaults: { _controller: SimplyTestableApiBundle:User:isEnabled, _format: json }      