jobs_list:
    pattern: /jobs/list/{limit}/
    defaults: { _controller: SimplyTestableApiBundle:Job:list, limit: 1, _format: json }    
    
job_crawl:
    pattern: /job/{site_root_url}/{test_id}/crawl/
    defaults: { _controller: SimplyTestableApiBundle:CrawlJob:start, _format: json }
    requirements:
        site_root_url: ".+"  

job_start:
    pattern: /job/{site_root_url}/start/
    defaults: { _controller: SimplyTestableApiBundle:JobStart:start, _format: json }
    requirements:
        site_root_url: ".+"
        
job_latest:        
  pattern: /job/{site_root_url}/latest/
  defaults: { _controller: SimplyTestableApiBundle:Job:latest, _format: json } 
  requirements:
    site_root_url: ".+"   
        
job_tasks:
  pattern: /job/{site_root_url}/{test_id}/tasks/
  defaults: { _controller: SimplyTestableApiBundle:Job:tasks, _format: json } 
  requirements:
    site_root_url: ".+"   
    
job_task_ids:
  pattern: /job/{site_root_url}/{test_id}/tasks/ids/
  defaults: { _controller: SimplyTestableApiBundle:Job:taskIds, _format: json } 
  requirements:
    site_root_url: ".+"     

job_list_urls:
    pattern: /job/{site_root_url}/{test_id}/urls/
    defaults: { _controller: SimplyTestableApiBundle:Job:listUrls, _format: json }    
    requirements:
        site_root_url: ".+"  
        
job_cancel:
    pattern: /job/{site_root_url}/{test_id}/cancel/
    defaults: { _controller: SimplyTestableApiBundle:Job:cancel, _format: json }    
    requirements:
        site_root_url: ".+"            
        
        
job_set_public:
    pattern: /job/{site_root_url}/{test_id}/set-public/
    defaults: { _controller: SimplyTestableApiBundle:Job:setPublic, _format: json }    
    requirements:
        site_root_url: ".+"           
        
job_set_private:
    pattern: /job/{site_root_url}/{test_id}/set-private/
    defaults: { _controller: SimplyTestableApiBundle:Job:setPrivate, _format: json }    
    requirements:
        site_root_url: ".+"          
        
        
job_is_public:
    pattern: /job/{site_root_url}/{test_id}/is_public/
    defaults: { _controller: SimplyTestableApiBundle:Job:isPublic, _format: json }    
    requirements:
        site_root_url: ".+"        
        
job:
    pattern: /job/{site_root_url}/{test_id}/
    defaults: { _controller: SimplyTestableApiBundle:Job:status, _format: json }    
    requirements:
        site_root_url: ".+"         
    
task_type_count:
  pattern: /tasks/{task_type}/{state_name}/count/
  defaults: { _controller: SimplyTestableApiBundle:Task:taskTypeCount, _format: json }         
   
        
worker_activate:
  pattern: /worker/activate/
  defaults: { _controller: SimplyTestableApiBundle:Worker:activate, _format: json }   
  
task_complete:
  pattern: /task/{worker_hostname}/{remote_task_id}/complete/
  defaults: { _controller: SimplyTestableApiBundle:Task:complete, _format: json }     
  
task_complete_by_url_and_task_type:
  pattern: /task/{canonical_url}/{task_type}/{parameter_hash}/complete/
  defaults: { _controller: SimplyTestableApiBundle:Task:completeByUrlAndTaskType, _format: json }     
  requirements:
      canonical_url: ".+"    
  
status:
  pattern: /
  defaults: { _controller: SimplyTestableApiBundle:Status:index, _format: json }     
  
user_create:
  pattern: /user/create/
  defaults: { _controller: SimplyTestableApiBundle:UserCreation:create, _format: json }   
  
user_activate_failure:
  pattern: /user/activate/
  defaults: { _controller: SimplyTestableApiBundle:UserCreation:activate, _format: json }  

user:
  pattern: /user/{email_canonical}/
  defaults: { _controller: SimplyTestableApiBundle:User:get, _format: json }                   
  
user_card_associate:
  pattern: /user/{email_canonical}/card/{stripe_card_token}/associate/
  defaults: { _controller: SimplyTestableApiBundle:UserAccountPlanSubscription:associateCard, _format: json }    
  
user_plan_subscribe:
  pattern: /user/{email_canonical}/{plan_name}/subscribe/
  defaults: { _controller: SimplyTestableApiBundle:UserAccountPlanSubscription:subscribe, _format: json }               
  
user_list_stripe_events:
  pattern: /user/{email_canonical}/stripe-events/{type}/
  defaults: { _controller: SimplyTestableApiBundle:UserStripeEvent:list, _format: json }      
  
user_activate:
  pattern: /user/activate/{token}/
  defaults: { _controller: SimplyTestableApiBundle:UserCreation:activate, _format: json }
  
user_get_token:
  pattern: /user/{email_canonical}/token/
  defaults: { _controller: SimplyTestableApiBundle:User:getToken, _format: json }    
  
user_reset_password:
  pattern: /user/reset-password/{token}/
  defaults: { _controller: SimplyTestableApiBundle:UserPasswordReset:resetPassword, _format: json }
  
user_exists:
  pattern: /user/{email_canonical}/exists/
  defaults: { _controller: SimplyTestableApiBundle:User:exists, _format: json }     
  
user_is_enabled:
  pattern: /user/{email_canonical}/enabled/
  defaults: { _controller: SimplyTestableApiBundle:User:isEnabled, _format: json }      

user_email_change_request_create:
  pattern: /user/{email_canonical}/email-change-request/{new_email}/create/
  defaults: { _controller: SimplyTestableApiBundle:UserEmailChange:create, _format: json }   
  
user_email_change_request_get:
  pattern: /user/{email_canonical}/email-change-request/
  defaults: { _controller: SimplyTestableApiBundle:UserEmailChange:get, _format: json }     
  
user_email_change_request_cancel:
  pattern: /user/{email_canonical}/email-change-request/cancel/
  defaults: { _controller: SimplyTestableApiBundle:UserEmailChange:cancel, _format: json }   
  
user_email_change_request_confirm:
  pattern: /user/{email_canonical}/email-change-request/{token}/
  defaults: { _controller: SimplyTestableApiBundle:UserEmailChange:confirm, _format: json }   
  
disable_readonly:
    pattern: /maintenance/disable-read-only/
    defaults: { _controller: SimplyTestableApiBundle:Maintenance:disableReadOnly, _format: json }            
        
enable_readonly:
    pattern: /maintenance/enable-read-only/
    defaults: { _controller: SimplyTestableApiBundle:Maintenance:enableReadOnly, _format: json }   
    
leave_readonly:
    pattern: /maintenance/leave-read-only/
    defaults: { _controller: SimplyTestableApiBundle:Maintenance:leaveReadOnly, _format: json }       
    
enable_backup_readonly:
    pattern: /maintenance/enable-backup-read-only/
    defaults: { _controller: SimplyTestableApiBundle:Maintenance:enableBackupReadOnly, _format: json }
    
stripe_webhook_receiver:
    pattern: /stripe/webhook/receiver/
    defaults: { _controller: SimplyTestableApiBundle:Stripe\WebHook:index, _format: json }    