jobs_list:
    pattern: /jobs/list/{limit}/
    defaults: { _controller: SimplyTestableApiBundle:Job:list, limit: 1, _format: json }    

job_start:
    pattern: /job/{site_root_url}/start/
    defaults: { _controller: SimplyTestableApiBundle:Job:start, _format: json }
    requirements:
        site_root_url: ".+"
        
job_tasks:
  pattern: /job/{site_root_url}/{test_id}/tasks/
  defaults: { _controller: SimplyTestableApiBundle:Job:tasks, _format: json } 
  requirements:
    site_root_url: ".+"   
        
job:
    pattern: /job/{site_root_url}/{test_id}/
    defaults: { _controller: SimplyTestableApiBundle:Job:status, _format: json }    
    requirements:
        site_root_url: ".+"
        
#    
#task_type_count:
#  pattern: /tasks/{task_type}/{state_name}/count/
#  defaults: { _controller: SimplyTestableApiBundle:Task:taskTypeCount, _format: json } 
#    
#     
#    
#test_results:
#    pattern: /job/{site_root_url}/{test_id}/results/
#    defaults: { _controller: SimplyTestableApiBundle:Job:results, _format: json }    
#    requirements:
#        site_root_url: ".+"
#        
#test_cancel:
#    pattern: /job/{site_root_url}/{test_id}/cancel/
#    defaults: { _controller: SimplyTestableApiBundle:Job:cancel, _format: json }    
#    requirements:
#        site_root_url: ".+"
#        
#test_list_urls:
#    pattern: /job/{site_root_url}/{test_id}/urls/
#    defaults: { _controller: SimplyTestableApiBundle:Job:listUrls, _format: json }    
#    requirements:
#        site_root_url: ".+"
#        
worker_activate:
  pattern: /worker/activate/
  defaults: { _controller: SimplyTestableApiBundle:Worker:activate, _format: json }   
#  
#task_complete:
#  pattern: /task/{worker_hostname}/{remote_task_id}/complete/
#  defaults: { _controller: SimplyTestableApiBundle:Task:complete, _format: json }     
#  
#status:
#  pattern: /status/
#  defaults: { _controller: SimplyTestableApiBundle:Status:index, _format: json }  
#        
#SimplyTestableApiBundle_homepage:
#    pattern:  /hello/{name}
#    defaults: { _controller: SimplyTestableApiBundle:Default:index }