job_joblist_list:
    pattern: /jobs/list/{limit}/{offset}/
    defaults: { _controller: SimplyTestableApiBundle:Job\JobList:list, _format: json }           
    
job_joblist_count:
    pattern: /jobs/list/count/
    defaults: { _controller: SimplyTestableApiBundle:Job\JobList:count, _format: json }      
    
job_joblist_websites:
    pattern: /jobs/list/websites/
    defaults: { _controller: SimplyTestableApiBundle:Job\JobList:websites, _format: json }          

job_start_start:
    pattern: /job/{site_root_url}/start/
    defaults: { _controller: SimplyTestableApiBundle:Job\Start:start, _format: json }
    requirements:
        site_root_url: ".+"
        
job_job_latest:        
  pattern: /job/{site_root_url}/latest/
  defaults: { _controller: SimplyTestableApiBundle:Job\Job:latest, _format: json } 
  requirements:
    site_root_url: ".+"   
        
job_job_tasks:
  pattern: /job/{site_root_url}/{test_id}/tasks/
  defaults: { _controller: SimplyTestableApiBundle:Job\Job:tasks, _format: json } 
  requirements:
    site_root_url: ".+"   
    
job_job_taskids:
  pattern: /job/{site_root_url}/{test_id}/tasks/ids/
  defaults: { _controller: SimplyTestableApiBundle:Job\Job:taskIds, _format: json } 
  requirements:
    site_root_url: ".+"     

job_job_listurls:
    pattern: /job/{site_root_url}/{test_id}/urls/
    defaults: { _controller: SimplyTestableApiBundle:Job\Job:listUrls, _format: json }    
    requirements:
        site_root_url: ".+"  
        
job_job_cancel:
    pattern: /job/{site_root_url}/{test_id}/cancel/
    defaults: { _controller: SimplyTestableApiBundle:Job\Job:cancel, _format: json }    
    requirements:
        site_root_url: ".+"            
        
        
job_job_setpublic:
    pattern: /job/{site_root_url}/{test_id}/set-public/
    defaults: { _controller: SimplyTestableApiBundle:Job\Job:setPublic, _format: json }    
    requirements:
        site_root_url: ".+"           
        
job_job_setprivate:
    pattern: /job/{site_root_url}/{test_id}/set-private/
    defaults: { _controller: SimplyTestableApiBundle:Job\Job:setPrivate, _format: json }    
    requirements:
        site_root_url: ".+"          
        
        
job_job_ispublic:
    pattern: /job/{site_root_url}/{test_id}/is_public/
    defaults: { _controller: SimplyTestableApiBundle:Job\Job:isPublic, _format: json }    
    requirements:
        site_root_url: ".+"        
        
job_start_retest:
    pattern: /job/{site_root_url}/{test_id}/re-test/
    defaults: { _controller: SimplyTestableApiBundle:Job\Start:retest, _format: json }    
    requirements:
        site_root_url: ".+"          
        
job_job_status:
    pattern: /job/{site_root_url}/{test_id}/
    defaults: { _controller: SimplyTestableApiBundle:Job\Job:status, _format: json }    
    requirements:
        site_root_url: ".+"
    
task_type_count:
  pattern: /tasks/{task_type}/{state_name}/count/
  defaults: { _controller: SimplyTestableApiBundle:Task:taskTypeCount, _format: json }         
   
        
worker_activate:
  pattern: /worker/activate/
  defaults: { _controller: SimplyTestableApiBundle:Worker:activate, _format: json }   
  
task_complete:
  pattern: /task/{worker_hostname}/{remote_task_id}/complete/
  defaults: { _controller: SimplyTestableApiBundle:Task:complete, _format: json }     
  
task_complete_by_url_and_task_type:
  pattern: /task/{canonical_url}/{task_type}/{parameter_hash}/complete/
  defaults: { _controller: SimplyTestableApiBundle:Task:completeByUrlAndTaskType, _format: json }     
  requirements:
      canonical_url: ".+"    
  
status:
  pattern: /
  defaults: { _controller: SimplyTestableApiBundle:Status:index, _format: json }     
  
user_create:
  pattern: /user/create/
  defaults: { _controller: SimplyTestableApiBundle:UserCreation:create, _format: json }   
  
user_activate_failure:
  pattern: /user/activate/
  defaults: { _controller: SimplyTestableApiBundle:UserCreation:activate, _format: json }  

user_get:
  pattern: /user/{email_canonical}/
  defaults: { _controller: SimplyTestableApiBundle:User:get, _format: json }

user_authenticate:
  pattern: /user/{email_canonical}/authenticate/
  defaults: { _controller: SimplyTestableApiBundle:User:authenticate, _format: json }
  
user_card_associate:
  pattern: /user/{email_canonical}/card/{stripe_card_token}/associate/
  defaults: { _controller: SimplyTestableApiBundle:UserAccountPlanSubscription:associateCard, _format: json }    
  
user_plan_subscribe:
  pattern: /user/{email_canonical}/{plan_name}/subscribe/
  defaults: { _controller: SimplyTestableApiBundle:UserAccountPlanSubscription:subscribe, _format: json }               
  
user_list_stripe_events:
  pattern: /user/{email_canonical}/stripe-events/{type}/
  defaults: { _controller: SimplyTestableApiBundle:UserStripeEvent:list, _format: json }      
  
user_activate:
  pattern: /user/activate/{token}/
  defaults: { _controller: SimplyTestableApiBundle:UserCreation:activate, _format: json }
  
user_get_token:
  pattern: /user/{email_canonical}/token/
  defaults: { _controller: SimplyTestableApiBundle:User:getToken, _format: json }    
  
user_reset_password:
  pattern: /user/reset-password/{token}/
  defaults: { _controller: SimplyTestableApiBundle:UserPasswordReset:resetPassword, _format: json }
  
user_exists:
  pattern: /user/{email_canonical}/exists/
  defaults: { _controller: SimplyTestableApiBundle:User:exists, _format: json }

user_hasinvites:
  pattern: /user/{email_canonical}/has-invites/
  defaults: { _controller: SimplyTestableApiBundle:User:hasInvites, _format: json }
  
user_is_enabled:
  pattern: /user/{email_canonical}/enabled/
  defaults: { _controller: SimplyTestableApiBundle:User:isEnabled, _format: json }      

user_email_change_request_create:
  pattern: /user/{email_canonical}/email-change-request/{new_email}/create/
  defaults: { _controller: SimplyTestableApiBundle:UserEmailChange:create, _format: json }   
  
user_email_change_request_get:
  pattern: /user/{email_canonical}/email-change-request/
  defaults: { _controller: SimplyTestableApiBundle:UserEmailChange:get, _format: json }     
  
user_email_change_request_cancel:
  pattern: /user/{email_canonical}/email-change-request/cancel/
  defaults: { _controller: SimplyTestableApiBundle:UserEmailChange:cancel, _format: json }   
  
user_email_change_request_confirm:
  pattern: /user/{email_canonical}/email-change-request/{token}/
  defaults: { _controller: SimplyTestableApiBundle:UserEmailChange:confirm, _format: json }   
  
disable_readonly:
    pattern: /maintenance/disable-read-only/
    defaults: { _controller: SimplyTestableApiBundle:Maintenance:disableReadOnly, _format: json }            
        
enable_readonly:
    pattern: /maintenance/enable-read-only/
    defaults: { _controller: SimplyTestableApiBundle:Maintenance:enableReadOnly, _format: json }   
    
leave_readonly:
    pattern: /maintenance/leave-read-only/
    defaults: { _controller: SimplyTestableApiBundle:Maintenance:leaveReadOnly, _format: json }       
    
enable_backup_readonly:
    pattern: /maintenance/enable-backup-read-only/
    defaults: { _controller: SimplyTestableApiBundle:Maintenance:enableBackupReadOnly, _format: json }
    
stripe_webhook_receiver:
    pattern: /stripe/webhook/receiver/
    defaults: { _controller: SimplyTestableApiBundle:Stripe\WebHook:index, _format: json }

team_create:
    pattern: /team/create/
    defaults: { _controller: SimplyTestableApiBundle:Team:create }

team_get:
    pattern: /team/
    defaults: { _controller: SimplyTestableApiBundle:Team:get}

teaminvite_accept:
    pattern: /team/invite/accept/
    defaults: { _controller: SimplyTestableApiBundle:TeamInvite:accept}

teaminvite_decline:
    pattern: /team/invite/decline/
    defaults: { _controller: SimplyTestableApiBundle:TeamInvite:decline}

teaminvite_get:
    pattern: /team/invite/{invitee_email}/
    defaults: { _controller: SimplyTestableApiBundle:TeamInvite:get}

team_remove:
    pattern: /team/remove/{member_email}/
    defaults: { _controller: SimplyTestableApiBundle:Team:remove }

team_leave:
    pattern: /team/leave/}
    defaults: { _controller: SimplyTestableApiBundle:Team:leave }

teaminvite_list:
    pattern: /team/invites/
    defaults: { _controller: SimplyTestableApiBundle:TeamInvite:list }

teaminvite_remove:
    pattern: /team/invite/{invitee_email}/remove/
    defaults: { _controller: SimplyTestableApiBundle:TeamInvite:remove }

teaminvite_userlist:
    pattern: /team/user/invites/
    defaults: { _controller: SimplyTestableApiBundle:TeamInvite:userList }