services:
  simplytestable.services.httpClient:
    class:  webignition\Http\Client\Client

  simplytestable.services.websiteservice:
    class:  SimplyTestable\ApiBundle\Services\WebSiteService
    arguments: 
        entityManager: "@doctrine.orm.entity_manager"
        httpClient: "@simplytestable.services.httpClient"
        
  simplytestable.services.stateservice:
    class:  SimplyTestable\ApiBundle\Services\StateService
    arguments: 
        entityManager: "@doctrine.orm.entity_manager" 
        
  simplytestable.services.taskservice:
    class:  SimplyTestable\ApiBundle\Services\TaskService
    arguments: 
        entityManager: "@doctrine.orm.entity_manager"      
        stateService: "@simplytestable.services.stateservice"
        resqueQueueService: "@simplytestable.services.resqueQueueService"
        
  simplytestable.services.jobservice:
    class:  SimplyTestable\ApiBundle\Services\JobService
    arguments: 
        entityManager: "@doctrine.orm.entity_manager"
        stateService: "@simplytestable.services.stateservice"
        taskService: "@simplytestable.services.taskservice"
        
  simplytestable.services.userservice:
    class:  SimplyTestable\ApiBundle\Services\UserService
    arguments:
        encoderFactory: "@security.encoder_factory"
        usernameCanonicalizer: "@fos_user.util.username_canonicalizer"
        emailCanonicalizer: "@fos_user.util.email_canonicalizer"
        objectManager: "@doctrine.orm.entity_manager"
        class: %fos_user.model.user.class%
        
  simplytestable.services.workerservice:
    class:  SimplyTestable\ApiBundle\Services\WorkerService
    arguments: 
        entityManager: "@doctrine.orm.entity_manager"
        workeractivationRequestService: "@simplytestable.services.workeractivationrequestservice"
        httpClient: "@simplytestable.services.httpClient"
        
  simplytestable.services.requestservice:
    class:   SimplyTestable\ApiBundle\Services\RequestService
    
  simplytestable.controller.action_listener:
    class: SimplyTestable\ApiBundle\EventListener\BeforeListener    
    arguments:
        logger: "@logger"
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }    
      
  simplytestable.services.workeractivationrequestservice:
    class:  SimplyTestable\ApiBundle\Services\WorkerActivationRequestService
    arguments: 
        entityManager: "@doctrine.orm.entity_manager"
        logger: "@logger"
        stateService: "@simplytestable.services.stateservice"
        httpClient: "@simplytestable.services.httpClient"
        urlService: "@simplytestable.services.urlService"
        
  simplytestable.services.urlService:
    class:  SimplyTestable\ApiBundle\Services\UrlService           
    
  simplytestable.services.resqueQueueService:
    class:   SimplyTestable\ApiBundle\Services\ResqueQueueService
    arguments:
      queueManager: "@glit_resque.queue_manager"
      logger: "@logger"
      resquePrefix: "%glit_resque.prefix%"

  simplytestable.services.workertaskservice:
    class:  SimplyTestable\ApiBundle\Services\WorkerTaskAssignmentService
    arguments: 
        entityManager: "@doctrine.orm.entity_manager"
        logger: "@logger"
        workerService: "@simplytestable.services.workerservice"
        stateService: "@simplytestable.services.stateservice"
        httpClient: "@simplytestable.services.httpClient"
        urlService: "@simplytestable.services.urlService"      
        taskService: "@simplytestable.services.taskservice"      
      
  simplytestable.services.workertaskassignmentservice:
    class:  SimplyTestable\ApiBundle\Services\WorkerTaskAssignmentService
    arguments: 
        entityManager: "@doctrine.orm.entity_manager"
        logger: "@logger"
        workerService: "@simplytestable.services.workerservice"
        stateService: "@simplytestable.services.stateservice"
        httpClient: "@simplytestable.services.httpClient"
        urlService: "@simplytestable.services.urlService"      
        taskService: "@simplytestable.services.taskservice"
        
  simplytestable.services.workertaskcancellationservice:
    class:  SimplyTestable\ApiBundle\Services\WorkerTaskCancellationService
    arguments: 
        entityManager: "@doctrine.orm.entity_manager"
        logger: "@logger"
        workerService: "@simplytestable.services.workerservice"
        stateService: "@simplytestable.services.stateservice"
        httpClient: "@simplytestable.services.httpClient"
        urlService: "@simplytestable.services.urlService"      
        taskService: "@simplytestable.services.taskservice"
        
  simplytestable.services.taskassignmentselectionservice:
    class:  SimplyTestable\ApiBundle\Services\TaskAssignmentSelectionService
    arguments:             
        jobService: "@simplytestable.services.jobservice"        
        taskService: "@simplytestable.services.taskservice" 
        logger: "@logger"
        
  simplytestable.services.tasktypeservice:
    class:  SimplyTestable\ApiBundle\Services\TaskTypeService
    arguments: 
        entityManager: "@doctrine.orm.entity_manager"      