services:
  simplytestable.services.httpClientService:
    class:  SimplyTestable\ApiBundle\Services\TestHttpClientService
    arguments:
        curlOptions: "%curl_options%"

  simplytestable.services.postmark.sender:
    class:   SimplyTestable\ApiBundle\Services\Postmark\TestSender

  simplytestable.repository.cronreport:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - Cron\CronBundle\Entity\CronReport

  simplytestable.repository.jobconfiguration:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\Job\Configuration

  simplytestable.repository.accountplanconstraint:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\Account\Plan\Constraint

  simplytestable.repository.jobammendment:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\Job\Ammendment

  simplytestable.repository.tasktypeoptions:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\Job\TaskTypeOptions

  simplytestable.repository.taskconfiguration:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\Job\TaskConfiguration

  simplytestable.repository.website:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\WebSite
