services:
  simplytestable.services.httpClientService:
    class:  SimplyTestable\ApiBundle\Services\TestHttpClientService
    
  simplytestable.services.userservice:
    class:  SimplyTestable\ApiBundle\Services\TestUserService
    arguments:
        encoderFactory: "@security.encoder_factory"
        usernameCanonicalizer: "@fos_user.util.username_canonicalizer"
        emailCanonicalizer: "@fos_user.util.email_canonicalizer"
        objectManager: "@doctrine.orm.entity_manager"
        class: %fos_user.model.user.class%
        tokenGeneratorClass: \FOS\UserBundle\Util\TokenGenerator    
        
  simplytestable.services.stripeService:
    class:   SimplyTestable\ApiBundle\Services\TestStripeService
    arguments: 
        apiKey: "%stripe_api_key%"         