imports:
    - { resource: services/http-client.yml }
    - { resource: services/web-resource-retriever.yml }
    - { resource: services/event-listeners.yml }
    - { resource: services/commands.yml }
    - { resource: services/legacy_aliases.yml }

services:
  simplytestable.session.handler:
    class: Symfony\Component\HttpFoundation\Session\Storage\Handler\NullSessionHandler

  webignition\Url\Resolver\Resolver:
    arguments:
      - '@GuzzleHttp\Client'

  webignition\WebResource\Sitemap\Factory:

  SimplyTestable\ApiBundle\Services\TaskPreProcessor\Factory:
    arguments:
      $taskPreprocessors:
        - '@SimplyTestable\ApiBundle\Services\TaskPreProcessor\LinkIntegrityTaskPreProcessor'

  SimplyTestable\ApiBundle\Services\UserAccountPlanService:
    arguments:
        $entityManager: '@doctrine.orm.entity_manager'
        $userService: '@SimplyTestable\ApiBundle\Services\UserService'
        $stripeService: '@SimplyTestable\ApiBundle\Services\StripeService'
        $teamService: '@SimplyTestable\ApiBundle\Services\Team\Service'
        $defaultTrialPeriod: '%default_trial_period%'

  SimplyTestable\ApiBundle\Services\StripeService:
    arguments:
        $apiKey: '%stripe_key%'

  SimplyTestable\ApiBundle\Services\TaskOutputJoiner\Factory:
    arguments:
      $taskPreprocessors:
        - '@SimplyTestable\ApiBundle\Services\TaskOutputJoiner\LinkIntegrityTaskOutputJoiner'

  SimplyTestable\ApiBundle\Services\TaskPostProcessor\Factory:
    arguments:
      $taskPreprocessors:
        - '@SimplyTestable\ApiBundle\Services\TaskPostProcessor\UrlDiscoveryTaskPostProcessor'

  SimplyTestable\ApiBundle\Services\TaskTypeDomainsToIgnoreService:
    arguments:
      $domainsToIgnoreByTaskType:
        "css validation": '%css_validation_domains_to_ignore%'
        "js static analysis": '%js_static_analysis_domains_to_ignore%'

  SimplyTestable\ApiBundle\Services\StripeWebHookMailNotificationSender:
    arguments:
      $mailService: '@SimplyTestable\ApiBundle\Services\Mail\Service'
      $parameters: "%stripe_webhook_developer_notification%"

  # Needs to be explicitly defined to be used in a resque context
  # Is otherwise autowired and autoconfigured correctly when injected from the main DIC
  SimplyTestable\ApiBundle\Services\Job\WebsiteResolutionService:
    arguments:
      $jobService: '@SimplyTestable\ApiBundle\Services\JobService'
      $httpClientService: '@SimplyTestable\ApiBundle\Services\HttpClientService'
      $websiteService: '@SimplyTestable\ApiBundle\Services\WebSiteService'
      $urlResolver: '@webignition\Url\Resolver\Resolver'
      $stateService: '@SimplyTestable\ApiBundle\Services\StateService'
      $entityManager: '@doctrine.orm.entity_manager'

  webignition\WebsiteSitemapFinder\WebsiteSitemapFinder:
    arguments:
      - '@GuzzleHttp\Client'

  webignition\WebsiteRssFeedFinder\WebsiteRssFeedFinder:
    arguments:
      - '@GuzzleHttp\Client'
