services:
  simplytestable.services.httpClientService:
    class:  SimplyTestable\ApiBundle\Services\TestHttpClientService
    arguments:
        curlOptions: "%curl_options%"

  simplytestable.services.postmark.sender:
    class:   SimplyTestable\ApiBundle\Services\Postmark\TestSender

  simplytestable.repository.taskconfiguration:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\Job\TaskConfiguration

  simplytestable.repository.website:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
        - SimplyTestable\ApiBundle\Entity\WebSite
